### PR TITLE
Added support for equality expressions (`==` and `!=`)

### PR DESCRIPTION
**Pull request by JasonHK**
The expressions were added in ReplayMod/preprocessor#3.

### CODE REVIEW

**Comment by FalseHonesty** [comment]
@JasonHK, it looks like this PR now has conflicts due to merging #2, if you could fix those up this should be a quick merge :)

**Comment by JasonHK** [comment]
> @JasonHK, it looks like this PR now has conflicts due to merging #2, if you could fix those up this should be a quick merge :)

@FalseHonesty The conflict have been resolved.

**Comment by FalseHonesty** [comment]
Great work on these PRs, I'll try and release a new plugin build today :)

**Comment by FalseHonesty** [comment]
Plugin v3.0.0 has been released :)

**Pull request merged**
